# Generated by Django 5.2 on 2025-04-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('application_date', models.DateField()),
                ('application_status', models.CharField(choices=[('waiting', 'Waiting'), ('interview', 'Interview Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='waiting', max_length=20)),
            ],
        ),
    ]
